### ISSUE TITLE
[feature request] sceneID support

### ISSUE THREAD

**Issue by nikolas** [datafruits/datafruits.old#7]
sceneID is an oauth service for demoscene websites. Datafruits isn't exactly a demoscene website, but maybe this would be cool?

https://id.scene.org/

If I'm lucky, I'll come up with a pull request.

**Comment by mcfiredrill** [comment]
:open_mouth: cool!

**Comment by mcfiredrill** [comment]
https://id.scene.org/docs/

> To access SceneID, your website is going to need an API key, which is a client ID and a client secret. You can obtain an API key by contacting us: tell us about your site and what you'd use SceneID for, and we'll provide you with the required credentials after you've set up.

Looks like we need to contact them first?
Are we too lamer to use it? :dizzy_face: 

Care to send them an email?

**Comment by nikolas** [comment]
Sure, but what email address should I send it from? gnu.org or riseup.net? I don't know which one's more scene. Nevermind, I'll try and log in to cooltoad. Woah.. cooltoad has changed!
![screen shot 2015-01-29 at 7 56 05 am](https://cloud.githubusercontent.com/assets/59292/5957858/4dfa0476-a78c-11e4-9bd6-0bd59b822186.png)
